"""
compare_BI.py
=============
Compares the Background Index (BI) estimates calculated with 'octopus' and 
'argonauts' modes for the same run.

Reads the CSV output files generated by analyze_BI_singlerun.py, performs a merge 
on common channels, prints a table to screen and produces a summary plot.
"""

import os
import argparse
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def main():
    parser = argparse.ArgumentParser(description="Compare BI between Octopus and Argonauts.")
    parser.add_argument("--run", type=str, default="m204", help="Run label (default: m204)")
    parser.add_argument("--out", type=str, default="BI_comparison.png", help="Name of the output graphic file")
    args = parser.parse_args()

    # Construction of expected paths for CSV files
    base_dir = os.path.dirname(os.path.abspath(__file__))
    file_octo = os.path.join(base_dir, f"{args.run}_results_octopus", f"BI_results_{args.run}_octopus.csv")
    file_argo = os.path.join(base_dir, f"{args.run}_results_argonauts", f"BI_results_{args.run}_argonauts.csv")

    # Check file existence
    if not os.path.exists(file_octo):
        print(f"[ERROR] File not found: {file_octo}")
        return
    if not os.path.exists(file_argo):
        print(f"[ERROR] File not found: {file_argo}")
        return

    # Load data
    df_octo = pd.read_csv(file_octo)
    df_argo = pd.read_csv(file_argo)

    # Rename columns (except 'channel') to distinguish the two sources
    df_octo = df_octo.add_suffix('_octo').rename(columns={'channel_octo': 'channel'})
    df_argo = df_argo.add_suffix('_argo').rename(columns={'channel_argo': 'channel'})

    # Merge on channels (keeps only channels present in BOTH files)
    df = pd.merge(df_octo, df_argo, on='channel', how='inner')
    df.sort_values('channel', inplace=True)
    df.reset_index(drop=True, inplace=True)

    if df.empty:
        print("[ERROR] No common channels found between the two CSV files.")
        return

    # Calculate relative differences and ratios
    # (Argonauts - Octopus) / Octopus [%]
    df['BI_diff_percent'] = ((df['BI_argo'] - df['BI_octo']) / df['BI_octo']) * 100
    df['BI_ratio'] = df['BI_argo'] / df['BI_octo']

    # ── TERMINAL OUTPUT ────────────────────────────────────────────────────────
    print(f"\nBI Comparison for run: {args.run}\n" + "="*70)
    print(f"{'Channel':>8} | {'BI Octopus':>15} | {'BI Argonauts':>15} | {'Diff (%)':>10} | {'Ratio (A/O)':>11}")
    print("-" * 70)
    for _, row in df.iterrows():
        print(f"{int(row['channel']):>8} | {row['BI_octo']:>15.3e} | {row['BI_argo']:>15.3e} | "
              f"{row['BI_diff_percent']:>9.2f}% | {row['BI_ratio']:>11.3f}")
    print("=" * 70 + "\n")

    # ── PLOTTING ───────────────────────────────────────────────────────────────
    plt.style.use('seaborn-v0_8-whitegrid')
    fig, axes = plt.subplots(1, 3, figsize=(18, 5))
    fig.suptitle(f"BI Estimates Comparison: Octopus vs Argonauts (Run {args.run})", fontsize=16, fontweight='bold')

    channels = df['channel'].astype(str)
    x = np.arange(len(channels))
    width = 0.35

    # [Panel 1] Side-by-side bar plot of BI per channel
    ax1 = axes[0]
    ax1.bar(x - width/2, df['BI_octo'], width, label='Octopus', color='steelblue')
    ax1.bar(x + width/2, df['BI_argo'], width, label='Argonauts', color='darkorange')
    ax1.set_xticks(x)
    ax1.set_xticklabels(channels)
    ax1.set_ylabel("Background Index (BI)")
    ax1.set_xlabel("Channel")
    ax1.set_title("BI per Channel")
    ax1.set_yscale('log')  # Useful if BI varies over many orders of magnitude
    ax1.legend()

    # [Panel 2] Scatter plot Octopus vs Argonauts with y=x bisector
    ax2 = axes[1]
    min_val = min(df['BI_octo'].min(), df['BI_argo'].min()) * 0.8
    max_val = max(df['BI_octo'].max(), df['BI_argo'].max()) * 1.2
    
    ax2.plot([min_val, max_val], [min_val, max_val], 'k--', alpha=0.5, label='y = x')
    sc = ax2.scatter(df['BI_octo'], df['BI_argo'], c=df['channel'], cmap='tab10', s=80, zorder=3)
    
    # Add text labels to points
    for i, txt in enumerate(channels):
        ax2.annotate(txt, (df['BI_octo'].iloc[i], df['BI_argo'].iloc[i]), 
                     xytext=(5, 5), textcoords='offset points', fontsize=9)
        
    ax2.set_xscale('log')
    ax2.set_yscale('log')
    ax2.set_xlabel("BI Octopus")
    ax2.set_ylabel("BI Argonauts")
    ax2.set_title("BI Correlation")
    ax2.legend()

    # [Panel 3] Percentage difference
    ax3 = axes[2]
    colors = ['crimson' if val < 0 else 'forestgreen' for val in df['BI_diff_percent']]
    ax3.bar(channels, df['BI_diff_percent'], color=colors)
    ax3.axhline(0, color='black', linewidth=1)
    ax3.set_ylabel("Difference % ((Argo - Octo) / Octo)")
    ax3.set_xlabel("Channel")
    ax3.set_title("Relative Deviation (%)")

    plt.tight_layout()
    plt.savefig(args.out, dpi=300)
    print(f"[OK] Plot saved to: {os.path.abspath(args.out)}")

if __name__ == "__main__":
    main()